### ISSUE TITLE
CreateModel 类名重复问题

### ISSUE THREAD

**Issue by wwdc14yh** [YouXianMing/iOS-General-Tools#1]
后台每个接口返回数据可能都会有相同key的字典  比如：

`{
    "content": {
        "street": "科技园路.",
        "city": "江苏苏州",
        "country": "中国"
    }
}`

`{
    "content": [
        "ddddd",
        "valawdawduew"
    ]
}`

生成model会有重复的`ContentModel`

解决：可以在每个`[key]model`前面加上`rootModelName` 相当于加上前缀

例如 `AModel` `BModel`  
         `AContentModel` `BContentModel`

**Comment by ws1227** [comment]
CreateModel还能用吗 命令换了吧  po [CreateModel  createModelWithJsonData:responseProject rootModelName:@"TempModel"]

**Comment by ws1227** [comment]
还能用
